# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Feb 24 05:37:57 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 637)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_button = QtGui.QPushButton(self.centralWidget)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout_3.addWidget(self.load_button)
        self.save_button = QtGui.QPushButton(self.centralWidget)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.concordance_list = QtGui.QListWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(12)
        self.concordance_list.setFont(font)
        self.concordance_list.setAlternatingRowColors(True)
        self.concordance_list.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.concordance_list.setObjectName("concordance_list")
        self.verticalLayout_4.addWidget(self.concordance_list)
        self.results_label = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.results_label.setFont(font)
        self.results_label.setObjectName("results_label")
        self.verticalLayout_4.addWidget(self.results_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tags_label = QtGui.QLabel(self.centralWidget)
        self.tags_label.setObjectName("tags_label")
        self.verticalLayout_3.addWidget(self.tags_label)
        self.tag_list = QtGui.QListWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tag_list.sizePolicy().hasHeightForWidth())
        self.tag_list.setSizePolicy(sizePolicy)
        self.tag_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tag_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tag_list.setObjectName("tag_list")
        self.verticalLayout_3.addWidget(self.tag_list)
        self.tag_deselect_button = QtGui.QPushButton(self.centralWidget)
        self.tag_deselect_button.setObjectName("tag_deselect_button")
        self.verticalLayout_3.addWidget(self.tag_deselect_button)
        self.attribute_label = QtGui.QLabel(self.centralWidget)
        self.attribute_label.setObjectName("attribute_label")
        self.verticalLayout_3.addWidget(self.attribute_label)
        self.attribute_search = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attribute_search.sizePolicy().hasHeightForWidth())
        self.attribute_search.setSizePolicy(sizePolicy)
        self.attribute_search.setMinimumSize(QtCore.QSize(200, 0))
        self.attribute_search.setObjectName("attribute_search")
        self.verticalLayout_3.addWidget(self.attribute_search)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ignore_tags_box = QtGui.QCheckBox(self.centralWidget)
        self.ignore_tags_box.setEnabled(True)
        self.ignore_tags_box.setChecked(False)
        self.ignore_tags_box.setObjectName("ignore_tags_box")
        self.horizontalLayout_4.addWidget(self.ignore_tags_box)
        self.strip_tags_box = QtGui.QCheckBox(self.centralWidget)
        self.strip_tags_box.setChecked(True)
        self.strip_tags_box.setObjectName("strip_tags_box")
        self.horizontalLayout_4.addWidget(self.strip_tags_box)
        self.ignore_case_box = QtGui.QCheckBox(self.centralWidget)
        self.ignore_case_box.setObjectName("ignore_case_box")
        self.horizontalLayout_4.addWidget(self.ignore_case_box)
        self.allow_overlap_box = QtGui.QCheckBox(self.centralWidget)
        self.allow_overlap_box.setObjectName("allow_overlap_box")
        self.horizontalLayout_4.addWidget(self.allow_overlap_box)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_button = QtGui.QPushButton(self.centralWidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout.addWidget(self.search_button)
        self.search_bar = QtGui.QLineEdit(self.centralWidget)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.lrbound = QtGui.QSpinBox(self.centralWidget)
        self.lrbound.setProperty("value", 20)
        self.lrbound.setObjectName("lrbound")
        self.horizontalLayout.addWidget(self.lrbound)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyXMLConc", None, QtGui.QApplication.UnicodeUTF8))
        self.load_button.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.concordance_list.setSortingEnabled(True)
        self.results_label.setText(QtGui.QApplication.translate("MainWindow", "0 Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tags_label.setText(QtGui.QApplication.translate("MainWindow", "Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.tag_deselect_button.setText(QtGui.QApplication.translate("MainWindow", "Deselect", None, QtGui.QApplication.UnicodeUTF8))
        self.attribute_label.setText(QtGui.QApplication.translate("MainWindow", "Attribute Search (e.g. a1=\"1\";a2=\"2\")", None, QtGui.QApplication.UnicodeUTF8))
        self.ignore_tags_box.setText(QtGui.QApplication.translate("MainWindow", "Ignore Tags Completely", None, QtGui.QApplication.UnicodeUTF8))
        self.strip_tags_box.setText(QtGui.QApplication.translate("MainWindow", "Strip Tags", None, QtGui.QApplication.UnicodeUTF8))
        self.ignore_case_box.setText(QtGui.QApplication.translate("MainWindow", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.allow_overlap_box.setText(QtGui.QApplication.translate("MainWindow", "Allow Overlap", None, QtGui.QApplication.UnicodeUTF8))
        self.search_button.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))

